apiVersion: 'nais.io/v1'
kind: 'Alert'
metadata:
  name: toi-kandidat-es-proxy
  namespace: toi
  labels:
    team: toi
spec:
  receivers:
    slack:
      channel: 'inkludering-alerts-prod'
  alerts:
    - alert: toi-kandidat-es-proxy
      severity: danger
      expr: sum(up{app="toi-kandidat-es-proxy", job="kubernetes-pods"}) == 0
      for: 1s
      description: Appen er nede (ingen Kubernetes-pods er oppe)
      action: "https://logs.adeo.no/goto/759333f826a4bd8cfaaf3a86a835e4a8"

    - alert: toi-kandidat-es-proxy
      expr: sum(increase(logd_messages_total{log_app="toi-kandidat-es-proxy",log_level="Error"}[10m])) > 0
      for: 1s
      description: Appen har logget en error
      action: "https://logs.adeo.no/goto/759333f826a4bd8cfaaf3a86a835e4a8"

    - alert: toi-kandidat-es-proxy
      severity: warning
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="toi-kandidat-es-proxy",log_level=~"Warning"}[5m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="toi-kandidat-es-proxy"}[5m]))) > 20
      for: 5m
      description: Økning i warnings
      action: "https://logs.adeo.no/goto/759333f826a4bd8cfaaf3a86a835e4a8"
