apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: toi-kandidat-es-proxy
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8300
  ingresses:
    - {{ ingress }}
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  azure:
    application:
      enabled: true
  openSearch:
    instance: kandidat
    access: admin
